name: row_calculator
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.7.0
  flutter_riverpod: ^2.3.6
  fpdart: ^0.6.0
  freezed_annotation: ^2.2.0
  reactive_forms: ^16.0.1
  path_provider: ^2.0.15
  path: ^1.8.3
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.7
  dropdown_button2: ^2.1.3
  intl: ^0.18.1
  flutter_multi_formatter: ^2.11.1
  material_design_icons_flutter: ^7.0.7296
  geolocator: ^9.0.2
  rename: ^2.1.1


dev_dependencies:
<<<<<<< Updated upstream
  auto_route_generator: ^7.2.0
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
=======
  auto_route_generator: ^4.2.0
  build_runner: ^2.4.6
  flutter_lints: ^2.0.1
>>>>>>> Stashed changes
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.1 

flutter:
  uses-material-design: true

dependency_overrides:
  analyzer: ^4.4.0