name: row_calculator
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^4.2.1
  flutter_riverpod: ^1.0.4
  fpdart: ^0.2.0
  freezed_annotation: ^2.1.0
  reactive_forms: ^13.0.0
  sembast: ^3.2.0+1
  path_provider: ^2.0.11
  path: ^1.8.1
  json_annotation: ^4.6.0
  flutter_svg: ^1.1.3
  rxdart: ^0.27.5
  dropdown_button2: ^1.8.1
  intl: ^0.17.0


dev_dependencies:
  auto_route_generator: ^4.2.0
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true

